name: Test

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: npm
        cache-dependency-path: |
          package-lock.json
    - name: Setup corepack
      run: |
        corepack enable npm
    - name: Install
      run: npm ci
    - name: Package
      run: npm pack

  example:
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm
        cache-dependency-path: |
          package-lock.json
    - name: Setup corepack
      run: |
        corepack enable npm
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - name: Install
      run: |
        npm ci
        cd example
        npm install
    - name: Run
      run: |
        cd example
        npm run cdk synth
    - name: Test
      run: |
        cd example
        sam local invoke -t ./cdk.out/LambdaRubyExample.template.json RubyFunction3_2

  test-finish:
    runs-on: ubuntu-latest
    needs:
    - test
    - example
    steps:
    - run: echo OK
